import { CampaignLevel } from '../../types/campaign';

const q = (...tiers: number[]): number[] => tiers;

export const CAMPAIGN_CHAPTERS = [
  'First Steps',
  "Challenger's Path",
  'Master the Dohyō',
  'Road to Yokozuna',
] as const;

export const CAMPAIGN_LEVELS: CampaignLevel[] = [
  { id:'career-01',index:0,chapter:1,title:'First Contact',subtitle:'Your first tachiai',objectiveText:'Create a Cherry',objective:{type:'CREATE_TIER',tier:2,count:1},techniqueText:'Finish in one shot',masteryText:'Keep all three rikishi',shotLimit:4,lives:3,saltCharges:0,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(1,1,1,2),initialFruits:[{tier:1,x:0,y:80}] },
  { id:'career-02',index:1,chapter:1,title:'Make a Lime',subtitle:'Build your first chain',objectiveText:'Create a Lime',objective:{type:'CREATE_TIER',tier:3,count:1},techniqueText:'Trigger a 2x fusion chain',masteryText:'Finish within four shots',shotLimit:6,lives:3,saltCharges:0,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(1,1,2,1,1,2),initialFruits:[{tier:2,x:0,y:70}] },
  { id:'career-03',index:2,chapter:1,title:'Pushout Practice',subtitle:'Read the beetle, then strike',objectiveText:'Push the Rotten Beetle out of the ring',objective:{type:'CLEAR_HAZARDS',count:1,kinds:['BUG'],physicalOnly:true},techniqueText:'Use a rim rebound',masteryText:'Lose no fruit',shotLimit:6,lives:3,saltCharges:0,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(2,2,1,2,2,2),initialHazards:[{kind:'BUG',x:0,y:-205}],encounterHint:'The beetle shows its next short scuttle. Lead the arrow and send it over the tawara.' },
  { id:'career-04',index:3,chapter:1,title:'Sacred Salt',subtitle:'Purify slippery ice',objectiveText:'Melt the Ice Cub with Sacred Salt',objective:{type:'CLEAR_HAZARDS',count:1,kinds:['ICE']},techniqueText:'Clear it with salt',masteryText:'Finish before shot three',shotLimit:5,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(2,1,2,1,2),initialHazards:[{kind:'ICE',x:0,y:-45}],encounterHint:'Ice keeps sliding after impact. Equip Salt, place the circle over it, then confirm.',recommendedSkill:'SALT' },
  { id:'career-05',index:4,chapter:1,title:'Palm Strike',subtitle:'Break the frozen guard',objectiveText:'Clear the cracked Ice Cub',objective:{type:'CLEAR_HAZARDS',count:1,kinds:['ICE']},techniqueText:'Shatter it with Palm Strike',techniqueRule:{type:'USE_SKILL',skill:'PALM_STRIKE'},masteryText:'Finish within three shots',shotLimit:6,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(3,2,3,2,3,3),initialHazards:[{kind:'ICE',x:0,y:-105}],encounterHint:'Palm Strike is now unlocked. Arm it before launching to shatter ice on contact.',recommendedSkill:'PALM_STRIKE' },
  { id:'career-06',index:5,chapter:1,title:"Tengu's Trial",subtitle:'Bait the charge, punish the flank',objectiveText:'Push Tengu Orange out of the ring',objective:{type:'DEFEAT_RIVAL',count:1},techniqueText:'Strike while Tengu is vulnerable',masteryText:'Keep two lives',shotLimit:14,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(3,2,3,2,3,2,3,3,2,3,3,3,3,3),initialHazards:[{kind:'BUG',x:-135,y:-65},{kind:'ICE',x:135,y:-65}],rivalId:'TENGU_ORANGE',rewardId:'TRAINING_MAWASHI',encounterHint:'His orange arrow is locked. Let the charge miss, then hit his exposed side on your next shot.',recommendedSkill:'PALM_STRIKE' },
  { id:'career-07',index:6,chapter:2,title:'Narrow Flanks',subtitle:'Read the ellipse',objectiveText:'Create a Strawberry',objective:{type:'CREATE_TIER',tier:4,count:1},techniqueText:'Merge beside the narrow flank',masteryText:'Finish within six shots',shotLimit:8,lives:3,saltCharges:1,arenaMode:'ELLIPTICAL',arenaCondition:'NONE',queue:q(2,2,3,2,2,3,2,3),initialFruits:[{tier:3,x:0,y:40}] },
  { id:'career-08',index:7,chapter:2,title:'Double Clearance',subtitle:'Control the rebound',objectiveText:'Push out two beetles',objective:{type:'CLEAR_HAZARDS',count:2,kinds:['BUG'],physicalOnly:true},techniqueText:'Remove both in one shot',masteryText:'Lose no fruit',shotLimit:10,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(3,2,3,2,3,2,3,2,3,3),initialHazards:[{kind:'BUG',x:-145,y:-150},{kind:'BUG',x:145,y:-150}] },
  { id:'career-09',index:8,chapter:2,title:'Icebreaker',subtitle:'Choose force or salt',objectiveText:'Clear two ice cubes',objective:{type:'CLEAR_HAZARDS',count:2,kinds:['ICE']},techniqueText:'Purify one with salt',masteryText:'Finish within five shots',shotLimit:8,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(2,3,2,3,2,3,3,3),initialHazards:[{kind:'ICE',x:-95,y:-115},{kind:'ICE',x:95,y:-115}] },
  { id:'career-10',index:9,chapter:2,title:'Controlled Power',subtitle:'Score with purpose',objectiveText:'Reach 1,500 points',objective:{type:'REACH_SCORE',score:1500},techniqueText:'Reach a 3x combo',masteryText:'Finish within eight shots',shotLimit:12,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(3,3,2,3,3,2,3,3,3,2,3,3),initialFruits:[{tier:3,x:-55,y:45},{tier:3,x:55,y:45}] },
  { id:'career-11',index:10,chapter:2,title:'One Beautiful Shot',subtitle:'A prepared puzzle',objectiveText:'Create an Orange',objective:{type:'CREATE_TIER',tier:6,count:1},techniqueText:'Finish with one launch',masteryText:'Keep all lives',shotLimit:4,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(5,3,3,4),initialFruits:[{tier:5,x:0,y:55}],brokenBales:[2] },
  { id:'career-12',index:11,chapter:2,title:"Cherry's Challenge",subtitle:'Weather the slap cone',objectiveText:'Defeat Cherry Slapper',objective:{type:'DEFEAT_RIVAL',count:1},techniqueText:'Win after baiting a missed slap',masteryText:'Keep two lives',shotLimit:14,lives:3,saltCharges:1,arenaMode:'ELLIPTICAL',arenaCondition:'NONE',queue:q(3,3,4,3,4,3,4,3,4,4,3,4,4,4),rivalId:'CHERRY_SLAPPER',rewardId:'CHERRY_BLOSSOM_BOWL' },
  { id:'career-13',index:12,chapter:3,title:'Sticky Situation',subtitle:'Work around wasabi',objectiveText:'Create an Orange',objective:{type:'CREATE_TIER',tier:6,count:1},techniqueText:'Use wasabi to stop a fruit',masteryText:'Finish within seven shots',shotLimit:10,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(4,4,5,4,4,5,4,5,5,5),initialFruits:[{tier:5,x:105,y:25}],initialHazards:[{kind:'WASABI',x:0,y:5}] },
  { id:'career-14',index:13,chapter:3,title:'Pepper Express',subtitle:'Ride the boost',objectiveText:'Push out one beetle',objective:{type:'CLEAR_HAZARDS',count:1,kinds:['BUG'],physicalOnly:true},techniqueText:'Use the chili boost',masteryText:'Finish within four shots',shotLimit:7,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(3,4,3,4,4,3,4),initialHazards:[{kind:'CHILI',x:0,y:45},{kind:'BUG',x:0,y:-220}] },
  { id:'career-15',index:14,chapter:3,title:'Cracked Tawara',subtitle:'Aim for the opening',objectiveText:'Push out two beetles',objective:{type:'CLEAR_HAZARDS',count:2,kinds:['BUG'],physicalOnly:true},techniqueText:'Use a broken rim gap',masteryText:'Lose no fruit',shotLimit:9,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(4,3,4,3,4,4,3,4,4),initialHazards:[{kind:'BUG',x:0,y:-215},{kind:'BUG',x:80,y:-195}],brokenBales:[0,1] },
  { id:'career-16',index:15,chapter:3,title:'Grippy Clay',subtitle:'Power through resistance',objectiveText:'Create an Apple',objective:{type:'CREATE_TIER',tier:7,count:1},techniqueText:'Complete a forceful clash',masteryText:'Finish within eight shots',shotLimit:12,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'GRIPPY_CLAY',queue:q(5,5,6,5,5,6,5,6,6,5,6,6),initialFruits:[{tier:6,x:0,y:35}] },
  { id:'career-17',index:16,chapter:3,title:'Wobble Balance',subtitle:'Control the heavy side',objectiveText:'Survive eight shots',objective:{type:'SURVIVE_SHOTS',count:8},techniqueText:'Keep the ring balanced',masteryText:'Lose no fruit',shotLimit:8,lives:3,saltCharges:1,arenaMode:'WOBBLE',arenaCondition:'NONE',queue:q(3,4,3,4,5,3,4,5),initialFruits:[{tier:6,x:-130,y:0}] },
  { id:'career-18',index:17,chapter:3,title:"Coconut's Fortress",subtitle:'Move the immovable',objectiveText:'Defeat Coconut Tank',objective:{type:'DEFEAT_RIVAL',count:1},techniqueText:'Break a Tawara bale',masteryText:'Keep two lives',shotLimit:16,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(5,5,6,5,6,5,6,6,5,6,6,6,5,6,6,6),rivalId:'COCONUT_TANK',rewardId:'SACRED_TAWARA_STYLE' },
  { id:'career-19',index:18,chapter:4,title:'Read the Breeze',subtitle:'Aim through the wind',objectiveText:'Create a Melon',objective:{type:'CREATE_TIER',tier:8,count:1},techniqueText:'Merge across the wind',masteryText:'Finish within nine shots',shotLimit:13,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'KAMIKAZE_WIND',queue:q(6,6,7,6,6,7,6,7,7,6,7,7,7),initialFruits:[{tier:7,x:0,y:35}] },
  { id:'career-20',index:19,chapter:4,title:'Closing Circle',subtitle:'Stand your ground',objectiveText:'Survive ten shots',objective:{type:'SURVIVE_SHOTS',count:10},techniqueText:'Save a fruit from the edge',masteryText:'Keep two lives',shotLimit:10,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'CLOSING_RING',queue:q(4,5,4,5,5,4,5,5,5,5) },
  { id:'career-21',index:20,chapter:4,title:'Twin Clearance',subtitle:'Master the shockwave',objectiveText:'Push out two hazards',objective:{type:'CLEAR_HAZARDS',count:2,physicalOnly:true},techniqueText:'Remove both in one shot',masteryText:'Finish within five shots',shotLimit:9,lives:3,saltCharges:1,arenaMode:'ELLIPTICAL',arenaCondition:'NONE',queue:q(5,6,5,6,6,5,6,6,6),initialHazards:[{kind:'ICE',x:-145,y:-155},{kind:'BUG',x:145,y:-155}] },
  { id:'career-22',index:21,chapter:4,title:'Watermelon Workshop',subtitle:'Prepare the champion',objectiveText:'Create a Watermelon',objective:{type:'CREATE_TIER',tier:10,count:1},techniqueText:'Trigger a Tsuppari clash',masteryText:'Finish within six shots',shotLimit:9,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(8,8,9,8,8,9,8,9,9),initialFruits:[{tier:9,x:0,y:15}] },
  { id:'career-23',index:22,chapter:4,title:"Champion's Gate",subtitle:'Use everything you learned',objectiveText:'Reach 4,000 points',objective:{type:'REACH_SCORE',score:4000},techniqueText:'Complete a 3x chain',masteryText:'Keep two lives',shotLimit:14,lives:3,saltCharges:1,arenaMode:'WOBBLE',arenaCondition:'NONE',queue:q(6,6,7,6,7,7,6,7,7,8,7,8,8,8),initialFruits:[{tier:7,x:-80,y:20},{tier:7,x:80,y:20}],initialHazards:[{kind:'WASABI',x:0,y:-65},{kind:'CHILI',x:0,y:95}] },
  { id:'career-24',index:23,chapter:4,title:'Grand Final',subtitle:'Claim the white rope',objectiveText:'Defeat the Dragonfruit Yokozuna',objective:{type:'DEFEAT_RIVAL',count:1},techniqueText:'Create a Yokozuna Pineapple',masteryText:'Keep two lives',shotLimit:18,lives:3,saltCharges:1,arenaMode:'CIRCULAR',arenaCondition:'NONE',queue:q(8,8,9,8,9,9,8,9,9,10,9,10,10,10,10,10,10,10),initialFruits:[{tier:10,x:-145,y:70},{tier:10,x:145,y:70}],rivalId:'DRAGONFRUIT_YOKOZUNA',rewardId:'CHAMPION_GOLD_MAWASHI' },
];

export function getCampaignLevel(id: string): CampaignLevel | undefined {
  return CAMPAIGN_LEVELS.find((level) => level.id === id);
}

export function getCampaignTechniqueText(level: CampaignLevel): string {
  const tracked = new Set([0, 1, 3, 4, 7, 8, 9, 10, 20, 22, 23]);
  return tracked.has(level.index)
    ? level.techniqueText
    : `Finish within ${Math.max(1, Math.floor(level.shotLimit * 0.6))} shots`;
}
